version: '3.8'
services:
  database:
    container_name: database
    image: 'postgres'
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
